# Generated by Django 3.0.6 on 2020-05-19 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UnitOfMeasure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('suffix', models.CharField(max_length=5)),
                ('floating', models.BooleanField()),
                ('precision', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Measurable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='measurer.Category')),
                ('unitOfMeasure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='measurer.UnitOfMeasure')),
            ],
        ),
        migrations.CreateModel(
            name='Expected',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField()),
                ('value', models.IntegerField(null=True)),
                ('value_float', models.FloatField(null=True)),
                ('measurable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='measurer.Measurable')),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField()),
                ('value', models.IntegerField(null=True)),
                ('value_float', models.FloatField(null=True)),
                ('measurable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='measurer.Measurable')),
            ],
        ),
    ]
