# Generated by Django 3.0.6 on 2020-05-19 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='value_float',
        ),
        migrations.RemoveField(
            model_name='expected',
            name='value_float',
        ),
    ]
